/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package managerv2;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author alandarev
 */
public class MainWindow extends javax.swing.JFrame {
  public All all;

  /**
   * Creates new form MainWindow
   */
  public MainWindow(All all) {
    this.all = all;
    all.window = this;
    initComponents();
    all.println("Initialized.");
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jFrame1 = new javax.swing.JFrame();
    jFrame2 = new javax.swing.JFrame();
    jFileChooser1 = new javax.swing.JFileChooser();
    parentFrame = new javax.swing.JPanel();
    infoFrame = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    mainFrame = new javax.swing.JPanel();
    mainMenu = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jMenuItem1 = new javax.swing.JMenuItem();
    jMenuItem2 = new javax.swing.JMenuItem();
    jMenuItem3 = new javax.swing.JMenuItem();
    jMenuItem4 = new javax.swing.JMenuItem();

    org.jdesktop.layout.GroupLayout jFrame1Layout = new org.jdesktop.layout.GroupLayout(jFrame1.getContentPane());
    jFrame1.getContentPane().setLayout(jFrame1Layout);
    jFrame1Layout.setHorizontalGroup(
      jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(0, 400, Short.MAX_VALUE)
    );
    jFrame1Layout.setVerticalGroup(
      jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(0, 300, Short.MAX_VALUE)
    );

    org.jdesktop.layout.GroupLayout jFrame2Layout = new org.jdesktop.layout.GroupLayout(jFrame2.getContentPane());
    jFrame2.getContentPane().setLayout(jFrame2Layout);
    jFrame2Layout.setHorizontalGroup(
      jFrame2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(0, 400, Short.MAX_VALUE)
    );
    jFrame2Layout.setVerticalGroup(
      jFrame2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(0, 300, Short.MAX_VALUE)
    );

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle(All.TITLE);

    jTextArea1.setEditable(false);
    jTextArea1.setColumns(20);
    jTextArea1.setLineWrap(true);
    jTextArea1.setRows(5);
    jTextArea1.setText("Starting up...\n");
    jScrollPane1.setViewportView(jTextArea1);

    org.jdesktop.layout.GroupLayout infoFrameLayout = new org.jdesktop.layout.GroupLayout(infoFrame);
    infoFrame.setLayout(infoFrameLayout);
    infoFrameLayout.setHorizontalGroup(
      infoFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, infoFrameLayout.createSequentialGroup()
        .add(0, 0, Short.MAX_VALUE)
        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 722, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
    );
    infoFrameLayout.setVerticalGroup(
      infoFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, infoFrameLayout.createSequentialGroup()
        .addContainerGap()
        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        .addContainerGap())
    );

    org.jdesktop.layout.GroupLayout mainFrameLayout = new org.jdesktop.layout.GroupLayout(mainFrame);
    mainFrame.setLayout(mainFrameLayout);
    mainFrameLayout.setHorizontalGroup(
      mainFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(0, 347, Short.MAX_VALUE)
    );
    mainFrameLayout.setVerticalGroup(
      mainFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(0, 560, Short.MAX_VALUE)
    );

    org.jdesktop.layout.GroupLayout parentFrameLayout = new org.jdesktop.layout.GroupLayout(parentFrame);
    parentFrame.setLayout(parentFrameLayout);
    parentFrameLayout.setHorizontalGroup(
      parentFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, parentFrameLayout.createSequentialGroup()
        .add(mainFrame, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .add(infoFrame, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    parentFrameLayout.setVerticalGroup(
      parentFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(infoFrame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .add(parentFrameLayout.createSequentialGroup()
        .add(mainFrame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    jMenu1.setText("File");

    jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.META_MASK));
    jMenuItem1.setText("New Project");
    jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuNewProject(evt);
      }
    });
    jMenu1.add(jMenuItem1);

    jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.META_MASK));
    jMenuItem2.setText("Open Project...");
    jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuOpenProject(evt);
      }
    });
    jMenu1.add(jMenuItem2);

    jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.META_MASK));
    jMenuItem3.setText("Save As...");
    jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem3ActionPerformed(evt);
      }
    });
    jMenu1.add(jMenuItem3);

    jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.META_MASK));
    jMenuItem4.setLabel("Export to SQL");
    jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem4ActionPerformed(evt);
      }
    });
    jMenu1.add(jMenuItem4);

    mainMenu.add(jMenu1);

    setJMenuBar(mainMenu);

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(parentFrame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(parentFrame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void menuNewProject(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewProject

    boolean pass=true;
    if(!all.isSafe()) {
      pass=false;
      

      int n = JOptionPane.showOptionDialog(this,
        "Progress will be lost. Continue?", "New Project...",
        JOptionPane.OK_CANCEL_OPTION,
        JOptionPane.QUESTION_MESSAGE, null, null, null);
      System.out.println("n = " + n);
      if(n == 0)  pass=true;

    }
    if(!pass) {
      all.println("New Project Cancelled by user");
      return;
    };
    all.Reset();
    all.println("New Project Initialized");
  }//GEN-LAST:event_menuNewProject

  private void menuOpenProject(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpenProject

    boolean pass=true;
    if(!all.isSafe()) {
      pass=false;
      

      int n = JOptionPane.showOptionDialog(this,
        "Progress will be lost. Continue?", "Open Project...",
        JOptionPane.OK_CANCEL_OPTION,
        JOptionPane.QUESTION_MESSAGE, null, null, null);
      System.out.println("n = " + n);
      if(n == 0)  pass=true;

    }
    if(!pass) {
      all.println("New Project Cancelled by user");
      return;
    };
    JFileChooser fc = new JFileChooser();
    int returnVal = fc.showOpenDialog(this);
    
    File file;
    if (returnVal == JFileChooser.APPROVE_OPTION) {
      file = fc.getSelectedFile();
    }
    else  {
      all.println("File not chosen");
      return;
    }

    all.Reset();
    all.setDisabled();
    all.LoadFile(file);

  }//GEN-LAST:event_menuOpenProject

  private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    JFileChooser fc = new JFileChooser();
    int returnVal = fc.showSaveDialog(this);
    File file;
    if (returnVal == JFileChooser.APPROVE_OPTION) {
      file = fc.getSelectedFile();
      all.writeToFile(file);
    }
    else  {
      all.println("Saving cancelled by user");
    }
  }//GEN-LAST:event_jMenuItem3ActionPerformed

  private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
    // Export to SQL
    String s = (String)JOptionPane.showInputDialog(
                    this,
                    "Please provide password to save Items into Server's SQL Database",
                    "Authentication",
                    JOptionPane.PLAIN_MESSAGE,
                    null,
                    null,
                    "");

    if ((s != null) && (s.length() > 0)) {
        all.saveToSQL("KdwIvew32Dwp");
    }
    else  {
      this.all.println("Password was not provided");
    }

    

  }//GEN-LAST:event_jMenuItem4ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JPanel infoFrame;
  private javax.swing.JFileChooser jFileChooser1;
  private javax.swing.JFrame jFrame1;
  private javax.swing.JFrame jFrame2;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JMenuItem jMenuItem2;
  private javax.swing.JMenuItem jMenuItem3;
  private javax.swing.JMenuItem jMenuItem4;
  private javax.swing.JScrollPane jScrollPane1;
  public javax.swing.JTextArea jTextArea1;
  public javax.swing.JPanel mainFrame;
  public javax.swing.JMenuBar mainMenu;
  public javax.swing.JPanel parentFrame;
  // End of variables declaration//GEN-END:variables
}
